USE CTC;

DROP TABLE  IF EXISTS CURRENCIES_CTC CASCADE;
CREATE TABLE CURRENCIES_CTC  (
    PRTY     INTEGER     NOT NULL DEFAULT 999
   ,SYMBOL   VARCHAR(8)  NOT NULL -- To Currency
   ,NAME     VARCHAR(64) NOT NULL -- From currency
   ,DECIMALS INTEGER     NOT NULL
   ,ACTIVE   TINYINT     NOT NULL
   ,FEE      DOUBLE                DEFAULT 0.0
   ,PRIMARY KEY ( SYMBOL )
);

COMMIT;    
