USE CTC;


-- Tabla general de SESSION
DROP TABLE  IF EXISTS SESSION_BASE CASCADE;
CREATE TABLE SESSION_BASE  (
    BASE     VARCHAR(10) NOT NULL -- Moneda base
   ,COUNTER  VARCHAR(10) NOT NULL -- Moneda evaluada
   ,TMS      TIMESTAMP   NOT NULL 
   ,OPEN     DOUBLE      NOT NULL 
   ,CLOSE    DOUBLE      NOT NULL 
   ,HIGH     DOUBLE      NOT NULL 
   ,LOW      DOUBLE      NOT NULL 
   ,VOLUME   DOUBLE      NOT NULL 
   ,QUOTEVOLUME DOUBLE      NOT NULL 
   ,AVERAGE  DOUBLE      NOT NULL 
   ,PRIMARY KEY ( TMS, BASE, COUNTER )
);


-- Cada tabla se llama SESSIONin - i Intervalo - n Periodos
-- SESSION mensuales
DROP TABLE  IF EXISTS SESSION_POL_M1 CASCADE;
CREATE TABLE SESSION_POL_M1 LIKE SESSION_BASE;

-- SESSION Semanales
DROP TABLE  IF EXISTS SESSION_POL_W1 CASCADE;
CREATE TABLE SESSION_POL_W1 LIKE SESSION_BASE;

-- SESSION Diarios
DROP TABLE  IF EXISTS SESSION_POL_D1 CASCADE;
CREATE TABLE SESSION_POL_D1 LIKE SESSION_BASE;

-- SESSION Horarios
-- En funcion de las horas que da poloniex

DROP TABLE  IF EXISTS SESSION_POL_H2 CASCADE;
CREATE TABLE SESSION_POL_H2 LIKE SESSION_BASE;

DROP TABLE  IF EXISTS SESSION_POL_H4 CASCADE;
CREATE TABLE SESSION_POL_H4 LIKE SESSION_BASE;

DROP TABLE  IF EXISTS SESSION_POL_H8 CASCADE;
CREATE TABLE SESSION_POL_H8 LIKE SESSION_BASE;

COMMIT;