USE CTC;
DELETE FROM PROVIDERS;

INSERT INTO PROVIDERS  (SYMBOL, NAME) VALUES ('POL',        'Poloniex'            );
INSERT INTO PROVIDERS  (SYMBOL, NAME) VALUES ('MKTCAP',     'CoinMarketCap'       );
COMMIT;
