USE CTC;
DELETE FROM CURRENCIES;

INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (1000, "Euro"                              ,"EUR"        , 0, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (1001, "Dolar"                              ,"USD"        , 0, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (   1, "1Credit"                              ,"1CR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (   2, "ArtByte"                              ,"ABY"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (   3, "AsiaCoin"                             ,"AC"         , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (   4, "AchieveCoin"                          ,"ACH"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (   5, "Aiden"                                ,"ADN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (   6, "Aeon"                                 ,"AEON"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (   7, "CryptoAero"                           ,"AERO"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (   8, "AirToken"                             ,"AIR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (   9, "Aphelion"                             ,"APH"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  10, "AuroraCoin"                           ,"AUR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  11, "AxisCoin"                             ,"AXIS"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  12, "SnowBalls"                            ,"BALLS"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  13, "BANK"                                 ,"BANK"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  14, "BitBlock"                             ,"BBL"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  15, "BoolBerry"                            ,"BBR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  16, "BitConnect"                           ,"BCC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  17, "Bytecoin"                             ,"BCN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  18, "Bollywood Coin"                       ,"BDC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  19, "BitDegree"                            ,"BDG"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  20, "BELA Coin"                            ,"BELA"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  21, "Bitstart"                             ,"BITS"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  22, "Black Coin"                           ,"BLK"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  23, "Block Net"                            ,"BLOCK"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  24, "BlueCoin"                             ,"BLU"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  25, "BonusCoin"                            ,"BNS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  26, "Bones Cryptocoin"                     ,"BONES"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  27, "BoostCoin"                            ,"BOST"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  28, "Bitcoin"                              ,"BTC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  29, "Bitcoin Dark"                         ,"BTCD"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  30, "Bitcoin Shop"                         ,"BTCS"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  31, "Bytom"                                ,"BTM"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  32, "Bitshares"                            ,"BTS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  33, "BURN Cryptocoin"                      ,"BURN"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  34, "Burst Cryptocoin"                     ,"BURST"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  35, "Coin 2.1"                             ,"C2"         , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  36, "CacheCoin"                            ,"CACH"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  37, "CAI Token"                            ,"CAI"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  38, "CyberCoin"                            ,"CC"         , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  39, "CannaCoin"                            ,"CCN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  40, "Cryptografic Anomaly"                 ,"CGA"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  41, "ChanceCoin"                           ,"CHA"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  42, "CinniCoin"                            ,"CINNI"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  43, "Clams"                                ,"CLAM"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  44, "ConcealCoin"                          ,"CNL"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  45, "CNMT"                                 ,"CNMT"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  46, "CryptoNote"                           ,"CNOTE"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  47, "COMM"                                 ,"COMM"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  48, "PayCon"                               ,"CON"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  49, "CorgiCoin"                            ,"CORG"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  50, "CryptCoin"                            ,"CRYPT"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  51, "CureCoin"                             ,"CURE"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  52, "Cycling Coin"                         ,"CYC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  53, "DigiByte"                             ,"DGB"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  54, "Etheroll"                             ,"DICE"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  55, "Carpe Diem Coin"                      ,"DIEM"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  56, "Dime Coin"                            ,"DIME"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  57, "Distrocoin"                           ,"DIS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  58, "DNSCrypt"                             ,"DNS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  59, "DogeCoin"                             ,"DOGE"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  60, "Dash"                                 ,"DASH"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  61, "Dark Cash"                            ,"DRKC"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  62, "DreamCoin"                            ,"DRM"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  63, "Dashcoin"                             ,"DSH"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  64, "DvoraKoin"                            ,"DVK"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  65, "EarthCoin"                            ,"EAC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  66, "Ebittree Coin"                        ,"EBT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  67, "ECC Coin"                             ,"ECC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  68, "e-Gulden"                             ,"EFL"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  69, "Einsteinium"                          ,"EMC2"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  70, "Emoticoint"                           ,"EMO"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  71, "EntropyCoin"                          ,"ENC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  72, "eTOK"                                 ,"eTOK"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  73, "ExeCoin"                              ,"EXE"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  74, "FAC"                                  ,"FAC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  75, "FantomCoin"                           ,"FCN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  76, "FIBRE Cryptocoin"                     ,"FIBRE"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  77, "FlappyCoin"                           ,"FLAP"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  78, "FoldingCoin"                          ,"FLDC"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  79, "FlutterCoin"                          ,"FLT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  80, "FoxCoin"                              ,"FOX"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  81, "FractalCoin"                          ,"FRAC"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  82, "Franko"                               ,"FRK"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  83, "FairQuark"                            ,"FRQ"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  84, "FVZCoin"                              ,"FVZ"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  85, "Frozen"                               ,"FZ"         , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  86, "Fuzon"                                ,"FZN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  87, "GapCoin"                              ,"GAP"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  88, "Global Denomination"                  ,"GDN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  89, "GetGems"                              ,"GEMZ"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  90, "GeoCoin"                              ,"GEO"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  91, "GIAR"                                 ,"GIAR"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  92, "Globe"                                ,"GLB"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  93, "GameCredits"                          ,"GAME"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  94, "Game League Coin"                     ,"GML"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  95, "Gnosis"                               ,"GNS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  96, "Crypto-Gold"                          ,"GOLD"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  97, "GROUPCoin"                            ,"GPC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  98, "GPUCoin"                              ,"GPUC"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES (  99, "Gridcoin Classic"                     ,"GRCX"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 100, "GroestlCoin"                          ,"GRS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 101, "GUE"                                  ,"GUE"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 102, "Hidrominer"                           ,"H2O"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 103, "HIRO"                                 ,"HIRO"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 104, "HOT"                                  ,"HOT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 105, "HUC"                                  ,"HUC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 106, "HVC"                                  ,"HVC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 107, "HYP"                                  ,"HYP"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 108, "HZ"                                   , "HZ"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 109, "IFC"                                  ,"IFC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 110, "ITC"                                  ,"ITC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 111, "IXC"                                  ,"IXC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 112, "JLH"                                  ,"JLH"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 113, "JPC"                                  ,"JPC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 114, "JUG"                                  ,"JUG"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 115, "KDC"                                  ,"KDC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 116, "KEY"                                  ,"KEY"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 117, "LC"                                   ,"LC"         , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 118, "LCL"                                  ,"LCL"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 119, "LEAF"                                 ,"LEAF"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 120, "LGC"                                  ,"LGC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 121, "LOL"                                  ,"LOL"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 122, "LOVE"                                 ,"LOVE"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 123, "LQD"                                  ,"LQD"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 124, "LTBC"                                 ,"LTBC"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 125, "Litecoin"                             ,"LTC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 126, "LTCX"                                 ,"LTCX"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 127, "MaidSafeCoin"                         ,"MAID"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 128, "MAST"                                 ,"MAST"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 129, "MAX"                                  ,"MAX"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 130, "MCN"                                  ,"MCN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 131, "MEC"                                  ,"MEC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 132, "METH"                                 ,"METH"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 133, "MIL"                                  ,"MIL"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 134, "MIN"                                  ,"MIN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 135, "MINT"                                 ,"MINT"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 136, "MMC"                                  ,"MMC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 137, "MMNXT"                                ,"MMNXT"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 138, "MMXIV"                                ,"MMXIV"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 139, "MNTA"                                 ,"MNTA"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 140, "MON"                                  ,"MON"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 141, "MRC"                                  ,"MRC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 142, "MRS"                                  ,"MRS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 143, "OMNI"                                 ,"OMNI"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 144, "MTS"                                  ,"MTS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 145, "MUN"                                  ,"MUN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 146, "MYR"                                  ,"MYR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 147, "MZC"                                  ,"MZC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 148, "N5X"                                  ,"N5X"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 149, "NAS"                                  ,"NAS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 150, "NAUT"                                 ,"NAUT"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 151, "NAV"                                  ,"NAV"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 152, "NBT"                                  ,"NBT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 153, "NEOS"                                 ,"NEOS"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 154, "NL"                                   ,"NL"         , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 155, "NMC"                                  ,"NMC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 156, "NOBL"                                 ,"NOBL"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 157, "NOTE"                                 ,"NOTE"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 158, "NOXT"                                 ,"NOXT"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 159, "NRS"                                  ,"NRS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 160, "NSR"                                  ,"NSR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 161, "NTX"                                  ,"NTX"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 162, "NXT Coin"                            ,"NXT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 163, "NXTI"                                 ,"NXTI"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 164, "OPAL"                                 ,"OPAL"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 165, "PAND"                                 ,"PAND"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 166, "PAWN"                                 ,"PAWN"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 167, "PIGGY"                                ,"PIGGY"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 168, "PINK"                                 ,"PINK"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 169, "PLX"                                  ,"PLX"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 170, "PMC"                                  ,"PMC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 171, "POT"                                  ,"POT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 172, "PPC"                                  ,"PPC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 173, "PRC"                                  ,"PRC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 174, "PRT"                                  ,"PRT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 175, "PTS"                                  ,"PTS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 176, "Q2C"                                  ,"Q2C"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 177, "QBK"                                  ,"QBK"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 178, "QCN"                                  ,"QCN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 179, "QORA"                                 ,"QORA"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 180, "QTL"                                  ,"QTL"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 181, "RBY"                                  ,"RBY"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 182, "ReddCoin"                             ,"RDD"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 183, "RIC"                                  ,"RIC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 184, "RZR"                                  ,"RZR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 185, "SDC"                                  ,"SDC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 186, "SHIBE"                                ,"SHIBE"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 187, "SHOPX"                                ,"SHOPX"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 188, "SILK"                                 ,"SILK"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 189, "SJCX"                                 ,"SJCX"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 190, "SLR"                                  ,"SLR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 191, "SMC"                                  ,"SMC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 192, "SOC"                                  ,"SOC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 193, "SPA"                                  ,"SPA"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 194, "SQL"                                  ,"SQL"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 195, "SRCC"                                 ,"SRCC"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 196, "SRG"                                  ,"SRG"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 197, "SSD"                                  ,"SSD"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 198, "STR"                                  ,"STR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 199, "SUM"                                  ,"SUM"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 200, "SUN"                                  ,"SUN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 201, "SWARM"                                ,"SWARM"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 202, "SXC"                                  ,"SXC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 203, "SYNC"                                 ,"YNC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 204, "SysCoin"                              ,"SYS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 205, "TalkCoin"                             ,"TAC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 206, "TORCoin"                              ,"TOR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 207, "Crypto Trust Network"                 ,"TRUST"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 208, "TWE"                                  ,"TWE"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 209, "Unitus"                               ,"UIS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 210, "Umbrella-LTC"                         ,"ULTC"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 211, "SuperNET"                             ,"UNITY"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 212, "UroCoin"                              ,"URO"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 213, "USDe Coin"                            ,"USDE"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 214, "Tether"                               ,"USDT"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 215, "UltraCoin"                            ,"UTC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 216, "UTIL"                                 ,"UTIL"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 217, "UniversityCoin"                       ,"UVC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 218, "Viacoin"                              ,"VIA"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 219, "Crypto VOOT"                          ,"VOOT"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 220, "VeriCoin"                             ,"VRC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 221, "Vertcoin"                             ,"VTC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 222, "WinCoin"                              ,"WC"         , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 223, "WorldCoin"                            ,"WDC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 224, "WIKI"                                 ,"WIKI"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 225, "CryptoWolf"                           ,"WOLF"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 226, "X13 Coin"                             ,"X13"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 227, "Sapience AIFX"                        ,"XAI"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 228, "Apollon"                              ,"XAP"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 229, "Bitcoin Plus"                         ,"XBC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 230, "XCurrency"                            ,"XC"         , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 231, "ClearingHouse"                        ,"XCH"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 232, "Crypton,ite"                          ,"XCN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 233, "CounterParty"                         ,"XCP"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 234, "Crypti"                               ,"XCR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 235, "DigitalNote"                          ,"XDN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 236, "DogeParty"                            ,"XDP"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 237, "HonorCoin"                            ,"XHC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 238, "LibertyCoin"                          ,"XLB"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 239, "Magi"                                 ,"XMG"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 240, "Monero"                               ,"XMR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 241, "PebbleCoin"                           ,"XPB"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 242, "PrimeCoin"                            ,"XPM"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 243, "Ripple"                               ,"XRP"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 244, "StabilityShares"                      ,"XSI"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 245, "Stealth"                              ,"XST"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 246, "SilliconValleyCoin"                   ,"XSV"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 247, "CoinoUSD"                             ,"XUSD"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 248, "Creds XXC"                            ,"XXC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 249, "YACCoin"                              ,"YACC"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 250, "YangCoin"                             ,"YANG"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 251, "YellowCoin"                           ,"YC"         , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 252, "YinCoin"                              ,"YIN"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 253, "VCash"                                ,"XVC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 254, "Florin"                               ,"FLO"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 256, "NEM/XEM"                              ,"XEM"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 258, "ARCHCoin"                             ,"ARCH"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 260, "CryptoHuge"                           ,"HUGE"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 261, "GridCoin"                             ,"GRC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 263, "I/O Coin"                             ,"IOC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 265, "INDEX"                                ,"INDEX"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 267, "Ethereum"                             ,"ETH"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 268, "Siacoin"                              ,"SC"         , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 269, "BitCrystals"                          ,"BCY"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 270, "Expanse"                              ,"EXP"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 271, "Factom"                               ,"FCT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 272, "bitUSD"                               ,"BITUSD"     , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 273, "bitCNY"                               ,"BITCNY"     , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 274, "Radium"                               ,"RADS"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 275, "HyperSpace"                           ,"AMP"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 276, "Voxels"                               ,"VOX"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 277, "Decred"                               ,"DCR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 278, "Lisk"                                 ,"LSK"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 279, "Decentralized Autonomous Organization","DAO"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 280, "LBRY Credits"                         ,"LBC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 281, "Steem"                                ,"STEEM"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 282, "Steem Dollars"                        ,"SBD"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 283, "Ethereum Classic"                     ,"ETC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 284, "Augur"                                ,"REP"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 285, "ARDR"                                 ,"ARDR"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 286, "ZCash"                                ,"ZEC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 287, "Stratis"                              ,"STRAT"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 288, "Nexium"                               ,"NXC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 289, "Pascal Coin"                          ,"PASC"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 290, "Golem"                                ,"GNT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 291, "Gnosis"                               ,"GNO"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 292, "Bitcoin Cash"                         ,"BCH"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 293, "0x"                                   ,"ZRX"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 294, "Civic"                                ,"CVC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 295, "OmiseGO"                              ,"OMG"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 296, "GAS Neo"                              ,"GAS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 297, "Decentralized Cloud Storage"          ,"STORJ"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 298, "Crypt/EOS"                            ,"EOS"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 299, "USD Coin"                             ,"USDC"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 300, "Status"                               ,"SNT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 301, "Kyber Network"                        ,"KNC"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 302, "Basic Attentio Token"                 ,"BAT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 303, "LOOM Networks"                        ,"LOOM"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 304, "Qtum"                                 ,"QTUM"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 305, "Bancor"                               ,"BNT"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 306, "Decentraland"                         ,"MANA"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 307, "FOAM Protocol"                        ,"FOAM"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 308, "Bitcoin Cash ABC"                     ,"BCHABC"     , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 309, "Bitcoin SV"                           ,"BCHSV"      , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 310, "Numerate"                             ,"NMR"        , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 311, "PolyMath"                             ,"POLY"       , 3, 0);
INSERT INTO CURRENCIES (ID, NAME, SYMBOL, DECIMALS, ACTIVE) VALUES ( 312, "Livepeer"                             ,"LPT"        , 3, 0);