USE CTC;


-- Tabla general de Tickers
DROP TABLE  IF EXISTS SESSIONS CASCADE;
CREATE TABLE SESSIONS  (
    BASE     VARCHAR    (6) NOT NULL -- Moneda base
   ,COUNTER  VARCHAR    (6) NOT NULL -- Moneda evaluada
   ,TMS      TIMESTAMP      NOT NULL 
   ,OPEN     DOUBLE         NOT NULL 
   ,CLOSE    DOUBLE         NOT NULL 
   ,HIGH     DOUBLE         NOT NULL 
   ,LOW      DOUBLE         NOT NULL 
   ,VOLUME   DOUBLE         NOT NULL 
   ,QUOTEVOLUME  DOUBLE         NOT NULL 
   ,WEIGHTEDAVERAGE DOUBLE         NOT NULL 
   ,PRIMARY KEY ( TMS, BASE, COUNTER )
);

-- Cada tabla se llama TICKERSin - i Intervalo - n Periodos
-- Tickers mensuales
DROP TABLE  IF EXISTS POL_TICKERSM1 CASCADE;
CREATE TABLE POL_TICKERSM1 LIKE SESSIONS;

-- Tickers Semanales
DROP TABLE  IF EXISTS POL_TICKERSW1 CASCADE;
CREATE TABLE POL_TICKERSW1 LIKE SESSIONS;

-- Tickers Diarios
DROP TABLE  IF EXISTS POL_TICKERSD1 CASCADE;
CREATE TABLE POL_TICKERSD1 LIKE SESSIONS;

-- Tickers Horarios
-- En funcion de las horas que da poloniex

DROP TABLE  IF EXISTS POL_TICKERSH2 CASCADE;
CREATE TABLE POL_TICKERSH2 LIKE SESSIONS;

DROP TABLE  IF EXISTS POL_TICKERSH4 CASCADE;
CREATE TABLE POL_TICKERSH4 LIKE SESSIONS;

DROP TABLE  IF EXISTS POL_TICKERSH8 CASCADE;
CREATE TABLE POL_TICKERSH8 LIKE SESSIONS;

COMMIT;