USE CTC;
DELETE FROM CURRENCIES_CTC;

INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "1CR"        , "1Credit"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ABY"        , "ArtByte"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "AC"         , "AsiaCoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ACH"        , "AchieveCoin"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ADN"        , "Aiden"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "AEON"       , "Aeon"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "AERO"       , "CryptoAero"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "AIR"        , "AirToken"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "APH"        , "Aphelion"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "AUR"        , "AuroraCoin"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "AXIS"       , "AxisCoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BALLS"      , "SnowBalls"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BANK"       , "BANK"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BBL"        , "BitBlock"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BBR"        , "BoolBerry"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BCC"        , "BitConnect"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BCN"        , "Bytecoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BDC"        , "Bollywood Coin"                       );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BDG"        , "BitDegree"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BELA"       , "BELA Coin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BITS"       , "Bitstart"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BLK"        , "Black Coin"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BLOCK"      , "Block Net"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BLU"        , "BlueCoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BNS"        , "BonusCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BONES"      , "Bones Cryptocoin"                     );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BOST"       , "BoostCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BTC"        , "Bitcoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BTCD"       , "Bitcoin Dark"                         );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BTCS"       , "Bitcoin Shop"                         );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BTM"        , "Bytom"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BTS"        , "Bitshares"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BURN"       , "BURN Cryptocoin"                      );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BURST"      , "Burst Cryptocoin"                     );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "C2"         , "Coin 2.1"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CACH"       , "CacheCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CAI"        , "CAI Token"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CC"         , "CyberCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CCN"        , "CannaCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CGA"        , "Cryptografic Anomaly"                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CHA"        , "ChanceCoin"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CINNI"      , "CinniCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CLAM"       , "Clams"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CNL"        , "ConcealCoin"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CNMT"       , "CNMT"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CNOTE"      , "CryptoNote"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "COMM"       , "COMM"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CON"        , "PayCon"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CORG"       , "CorgiCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CRYPT"      , "CryptCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CURE"       , "CureCoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CYC"        , "Cycling Coin"                         );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DGB"        , "DigiByte"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DICE"       , "Etheroll"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DIEM"       , "Carpe Diem Coin"                      );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DIME"       , "Dime Coin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DIS"        , "Distrocoin"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DNS"        , "DNSCrypt"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DOGE"       , "DogeCoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DASH"       , "Dash"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DRKC"       , "Dark Cash"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DRM"        , "DreamCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DSH"        , "Dashcoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DVK"        , "DvoraKoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "EAC"        , "EarthCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "EBT"        , "Ebittree Coin"                        );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ECC"        , "ECC Coin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "EFL"        , "e-Gulden"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "EMC2"       , "Einsteinium"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "EMO"        , "Emoticoint"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ENC"        , "EntropyCoin"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "eTOK"       , "eTOK"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "EXE"        , "ExeCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FAC"        , "FAC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FCN"        , "FantomCoin"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FIBRE"      , "FIBRE Cryptocoin"                     );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FLAP"       , "FlappyCoin"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FLDC"       , "FoldingCoin"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FLT"        , "FlutterCoin"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FOX"        , "FoxCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FRAC"       , "FractalCoin"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FRK"        , "Franko"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FRQ"        , "FairQuark"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FVZ"        , "FVZCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FZ"         , "Frozen"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FZN"        , "Fuzon"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GAP"        , "GapCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GDN"        , "Global Denomination"                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GEMZ"       , "GetGems"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GEO"        , "GeoCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GIAR"       , "GIAR"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GLB"        , "Globe"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GAME"       , "GameCredits"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GML"        , "Game League Coin"                     );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GNS"        , "Gnosis"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GOLD"       , "Crypto-Gold"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GPC"        , "GROUPCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GPUC"       , "GPUCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GRCX"       , "Gridcoin Classic"                     );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GRS"        , "GroestlCoin"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GUE"        , "GUE"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "H2O"        , "Hidrominer"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "HIRO"       , "HIRO"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "HOT"        , "HOT"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "HUC"        , "HUC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "HVC"        , "HVC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "HYP"        , "HYP"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6,  "HZ"        , "HZ"                                   );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "IFC"        , "IFC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ITC"        , "ITC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "IXC"        , "IXC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "JLH"        , "JLH"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "JPC"        , "JPC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "JUG"        , "JUG"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "KDC"        , "KDC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "KEY"        , "KEY"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LC"         , "LC"                                   );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LCL"        , "LCL"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LEAF"       , "LEAF"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LGC"        , "LGC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LOL"        , "LOL"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LOVE"       , "LOVE"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LQD"        , "LQD"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LTBC"       , "LTBC"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LTC"        , "Litecoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LTCX"       , "LTCX"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MAID"       , "MaidSafeCoin"                         );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MAST"       , "MAST"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MAX"        , "MAX"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MCN"        , "MCN"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MEC"        , "MEC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "METH"       , "METH"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MIL"        , "MIL"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MIN"        , "MIN"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MINT"       , "MINT"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MMC"        , "MMC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MMNXT"      , "MMNXT"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MMXIV"      , "MMXIV"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MNTA"       , "MNTA"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MON"        , "MON"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MRC"        , "MRC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MRS"        , "MRS"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "OMNI"       , "OMNI"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MTS"        , "MTS"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MUN"        , "MUN"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MYR"        , "MYR"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MZC"        , "MZC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "N5X"        , "N5X"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NAS"        , "NAS"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NAUT"       , "NAUT"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NAV"        , "NAV"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NBT"        , "NBT"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NEOS"       , "NEOS"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NL"         , "NL"                                   );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NMC"        , "NMC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NOBL"       , "NOBL"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NOTE"       , "NOTE"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NOXT"       , "NOXT"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NRS"        , "NRS"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NSR"        , "NSR"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NTX"        , "NTX"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NXT"        , "NXT Coin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NXTI"       , "NXTI"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "OPAL"       , "OPAL"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "PAND"       , "PAND"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "PAWN"       , "PAWN"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "PIGGY"      , "PIGGY"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "PINK"       , "PINK"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "PLX"        , "PLX"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "PMC"        , "PMC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "POT"        , "POT"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "PPC"        , "PPC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "PRC"        , "PRC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "PRT"        , "PRT"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "PTS"        , "PTS"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "Q2C"        , "Q2C"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "QBK"        , "QBK"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "QCN"        , "QCN"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "QORA"       , "QORA"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "QTL"        , "QTL"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "RBY"        , "RBY"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "RDD"        , "ReddCoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "RIC"        , "RIC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "RZR"        , "RZR"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SDC"        , "SDC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SHIBE"      , "SHIBE"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SHOPX"      , "SHOPX"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SILK"       , "SILK"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SJCX"       , "SJCX"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SLR"        , "SLR"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SMC"        , "SMC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SOC"        , "SOC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SPA"        , "SPA"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SQL"        , "SQL"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SRCC"       , "SRCC"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SRG"        , "SRG"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SSD"        , "SSD"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "STR"        , "STR"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SUM"        , "SUM"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SUN"        , "SUN"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SWARM"      , "SWARM"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SXC"        , "SXC"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "YNC"        , "SYNC"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SYS"        , "SysCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "TAC"        , "TalkCoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "TOR"        , "TORCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "TRUST"      , "Crypto Trust Network"                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "TWE"        , "TWE"                                  );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "UIS"        , "Unitus"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ULTC"       , "Umbrella-LTC"                         );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "UNITY"      , "SuperNET"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "URO"        , "UroCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "USDE"       , "USDe Coin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "USDT"       , "Tether"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "UTC"        , "UltraCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "UTIL"       , "UTIL"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "UVC"        , "UniversityCoin"                       );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "VIA"        , "Viacoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "VOOT"       , "Crypto VOOT"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "VRC"        , "VeriCoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "VTC"        , "Vertcoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "WC"         , "WinCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "WDC"        , "WorldCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "WIKI"       , "WIKI"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "WOLF"       , "CryptoWolf"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "X13"        , "X13 Coin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XAI"        , "Sapience AIFX"                        );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XAP"        , "Apollon"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XBC"        , "Bitcoin Plus"                         );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XC"         , "XCurrency"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XCH"        , "ClearingHouse"                        );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XCN"        , "Crypton,ite"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XCP"        , "CounterParty"                         );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XCR"        , "Crypti"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XDN"        , "DigitalNote"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XDP"        , "DogeParty"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XHC"        , "HonorCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XLB"        , "LibertyCoin"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XMG"        , "Magi"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XMR"        , "Monero"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XPB"        , "PebbleCoin"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XPM"        , "PrimeCoin"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XRP"        , "Ripple"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XSI"        , "StabilityShares"                      );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XST"        , "Stealth"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XSV"        , "SilliconValleyCoin"                   );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XUSD"       , "CoinoUSD"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XXC"        , "Creds XXC"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "YACC"       , "YACCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "YANG"       , "YangCoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "YC"         , "YellowCoin"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "YIN"        , "YinCoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XVC"        , "VCash"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FLO"        , "Florin"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "XEM"        , "NEM/XEM"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ARCH"       , "ARCHCoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "HUGE"       , "CryptoHuge"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GRC"        , "GridCoin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "IOC"        , "I/O Coin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "INDEX"      , "INDEX"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ETH"        , "Ethereum"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SC"         , "Siacoin"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BCY"        , "BitCrystals"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "EXP"        , "Expanse"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FCT"        , "Factom"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BITUSD"     , "bitUSD"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BITCNY"     , "bitCNY"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "RADS"       , "Radium"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "AMP"        , "HyperSpace"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "VOX"        , "Voxels"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DCR"        , "Decred"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LSK"        , "Lisk"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "DAO"        , "Decentralized Autonomous Organization");
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LBC"        , "LBRY Credits"                         );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "STEEM"      , "Steem"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SBD"        , "Steem Dollars"                        );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ETC"        , "Ethereum Classic"                     );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "REP"        , "Augur"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ARDR"       , "ARDR"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ZEC"        , "ZCash"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "STRAT"      , "Stratis"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NXC"        , "Nexium"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "PASC"       , "Pascal Coin"                          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GNT"        , "Golem"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GNO"        , "Gnosis"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BCH"        , "Bitcoin Cash"                         );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "ZRX"        , "0x"                                   );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "CVC"        , "Civic"                                );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "OMG"        , "OmiseGO"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "GAS"        , "GAS Neo"                              );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "STORJ"      , "Decentralized Cloud Storage"          );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "EOS"        , "Crypt/EOS"                            );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "USDC"       , "USD Coin"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "SNT"        , "Status"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "KNC"        , "Kyber Network"                        );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BAT"        , "Basic Attentio Token"                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LOOM"       , "LOOM Networks"                        );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "QTUM"       , "Qtum"                                 );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BNT"        , "Bancor"                               );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "MANA"       , "Decentraland"                         );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "FOAM"       , "FOAM Protocol"                        );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BCHABC"     , "Bitcoin Cash ABC"                     );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "BCHSV"      , "Bitcoin SV"                           );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "NMR"        , "Numerate"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "POLY"       , "PolyMath"                             );
INSERT INTO CURRENCIES_CTC (ACTIVE, DECIMALS, SYMBOL, NAME) VALUES ( 1, 6, "LPT"        , "Livepeer"                             );